services: 

  app_data_db:
    image: postgres:latest
    container_name: metabase_db
    env_file:
      - ./config/postgres.env
    volumes:
      - metabase_app_data:/var/lib/postgresql/data/
    ports:
      - 54320:5432
    restart: always

  ui_app_data_db:
    image: adminer
    container_name: adminer_mbdb_cnnct
    restart: always
    depends_on: 
      - app_data_db
    env_file:
      - ./config/adminer.env
    ports:
      - 8080:8080

  metabase:
    image: metabase/metabase:latest
    container_name: mtbse_cont
    restart: always
    depends_on:
      - app_data_db
    env_file:
      - ./config/metabase.env
    ports:
      - 3000:3000

  analysis-data_db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./config/mysql.env
    volumes:
      - metabase_analysis_data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    
  ui_analysis_data_db:
    image: adminer
    environment:
      ADMINER_DESIGN: rmsoft
      ADMINER_DEFAULT_SERVER: analysis-data_db
    ports:
      - "8081:8080"
    restart: always

volumes: 
  metabase_app_data:
  metabase_analysis_data:




    